import type { LucideIcon } from 'lucide-react';
import {
  Users,
  CheckCheck,
  Briefcase,
  TrendingDown,
  FileClock,
  CalendarOff,
  CalendarClock,
  Timer,
  CircleCheck,
  Clock,
  CalendarDays,
  FileText,
  Scale,
  Banknote,
  FileStack,
  ShieldCheck,
  ShieldAlert,
  FileWarning,
  Percent,
} from 'lucide-react';
import type { AdminKpiCategory, AdminKpiSlug } from './admin-dashboard.types';

export interface AdminKpiCatalogEntry {
  slug: AdminKpiSlug;
  category: AdminKpiCategory;
  permission: string;
  icon: LucideIcon;
  iconColor: string;
  bgColor: string;
  borderColor: string;
  containerClass: string;
  iconClass: string;
  trend?: 'up' | 'down';
  titleKey: string;
  descKey: string;
  statsTitleKey?: string;
}

export const DEFAULT_ADMIN_KPI_SLUGS: AdminKpiSlug[] = [
  'total_employees',
  'pending_approve',
  'upcoming_payroll',
  'active_employees',
];

export const MAX_ADMIN_KPI_CARDS = 8;

export const ADMIN_KPI_CATALOG: AdminKpiCatalogEntry[] = [
  {
    slug: 'total_employees',
    category: 'workforce',
    permission: 'employees:read',
    icon: Users,
    iconColor: '#D97706',
    bgColor: 'rgba(217, 119, 6, 0.05)',
    borderColor: 'rgba(217, 119, 6, 0.5)',
    containerClass: 'bg-[rgba(217,119,6,0.05)] border-orange-200/50',
    iconClass: 'text-[#D97706]',
    trend: 'up',
    titleKey: 'edit.kpis.totalEmployees.title',
    descKey: 'edit.kpis.totalEmployees.desc',
    statsTitleKey: 'stats.totalEmployees',
  },
  {
    slug: 'active_employees',
    category: 'workforce',
    permission: 'attendance:read',
    icon: CheckCheck,
    iconColor: '#22C55E',
    bgColor: 'rgba(34, 197, 94, 0.05)',
    borderColor: 'rgba(34, 197, 94, 0.5)',
    containerClass: 'bg-[rgba(34,197,94,0.05)] border-green-200/50',
    iconClass: 'text-[#22C55E]',
    trend: 'up',
    titleKey: 'edit.kpis.activeEmployees.title',
    descKey: 'edit.kpis.activeEmployees.desc',
    statsTitleKey: 'stats.activeEmployees',
  },
  {
    slug: 'new_hires',
    category: 'workforce',
    permission: 'employees:read',
    icon: Briefcase,
    iconColor: '#A855F7',
    bgColor: 'rgba(168, 85, 247, 0.05)',
    borderColor: 'rgba(168, 85, 247, 0.5)',
    containerClass: 'bg-[rgba(168,85,247,0.05)] border-purple-200/50',
    iconClass: 'text-[#A855F7]',
    trend: 'up',
    titleKey: 'edit.kpis.newHires.title',
    descKey: 'edit.kpis.newHires.desc',
    statsTitleKey: 'edit.kpis.newHires.title',
  },
  {
    slug: 'attrition_rate',
    category: 'workforce',
    permission: 'employees:read',
    icon: TrendingDown,
    iconColor: '#D97706',
    bgColor: 'rgba(217, 119, 6, 0.05)',
    borderColor: 'rgba(217, 119, 6, 0.5)',
    containerClass: 'bg-[rgba(217,119,6,0.05)] border-orange-200/50',
    iconClass: 'text-[#D97706]',
    trend: 'down',
    titleKey: 'edit.kpis.attritionRate.title',
    descKey: 'edit.kpis.attritionRate.desc',
    statsTitleKey: 'edit.kpis.attritionRate.title',
  },
  {
    slug: 'pending_approve',
    category: 'leave',
    permission: 'leave_requests:read',
    icon: FileClock,
    iconColor: '#8A38F5',
    bgColor: 'rgba(138, 56, 245, 0.05)',
    borderColor: 'rgba(138, 56, 245, 0.5)',
    containerClass: 'bg-[rgba(138,56,245,0.05)] border-purple-200/50',
    iconClass: 'text-[#8A38F5]',
    trend: 'down',
    titleKey: 'edit.kpis.pendingApprove.title',
    descKey: 'edit.kpis.pendingApprove.desc',
    statsTitleKey: 'stats.pendingApprove',
  },
  {
    slug: 'on_leave_today',
    category: 'attendance',
    permission: 'attendance:read',
    icon: CalendarOff,
    iconColor: '#F59E0B',
    bgColor: 'rgba(245, 158, 11, 0.05)',
    borderColor: 'rgba(245, 158, 11, 0.5)',
    containerClass: 'bg-[rgba(245,158,11,0.05)] border-amber-200/50',
    iconClass: 'text-[#F59E0B]',
    titleKey: 'edit.kpis.onLeaveToday.title',
    descKey: 'edit.kpis.onLeaveToday.desc',
    statsTitleKey: 'edit.kpis.onLeaveToday.title',
  },
  {
    slug: 'attendance_rate',
    category: 'attendance',
    permission: 'attendance:read',
    icon: CalendarClock,
    iconColor: '#22C55E',
    bgColor: 'rgba(34, 197, 94, 0.05)',
    borderColor: 'rgba(34, 197, 94, 0.5)',
    containerClass: 'bg-[rgba(34,197,94,0.05)] border-green-200/50',
    iconClass: 'text-[#22C55E]',
    trend: 'up',
    titleKey: 'edit.kpis.attendanceRate.title',
    descKey: 'edit.kpis.attendanceRate.desc',
    statsTitleKey: 'edit.kpis.attendanceRate.title',
  },
  {
    slug: 'pending_overtime',
    category: 'attendance',
    permission: 'attendance:read',
    icon: Clock,
    iconColor: '#F59E0B',
    bgColor: 'rgba(245, 158, 11, 0.05)',
    borderColor: 'rgba(245, 158, 11, 0.5)',
    containerClass: 'bg-[rgba(245,158,11,0.05)] border-amber-200/50',
    iconClass: 'text-[#F59E0B]',
    titleKey: 'edit.kpis.pendingOvertime.title',
    descKey: 'edit.kpis.pendingOvertime.desc',
    statsTitleKey: 'edit.kpis.pendingOvertime.title',
  },
  {
    slug: 'approved_overtime',
    category: 'attendance',
    permission: 'attendance:read',
    icon: CircleCheck,
    iconColor: '#22C55E',
    bgColor: 'rgba(34, 197, 94, 0.05)',
    borderColor: 'rgba(34, 197, 94, 0.5)',
    containerClass: 'bg-[rgba(34,197,94,0.05)] border-green-200/50',
    iconClass: 'text-[#22C55E]',
    titleKey: 'edit.kpis.approvedOvertime.title',
    descKey: 'edit.kpis.approvedOvertime.desc',
    statsTitleKey: 'edit.kpis.approvedOvertime.title',
  },
  {
    slug: 'total_overtime_hours',
    category: 'attendance',
    permission: 'attendance:read',
    icon: Timer,
    iconColor: '#04A4C4',
    bgColor: 'rgba(4, 164, 196, 0.05)',
    borderColor: 'rgba(4, 164, 196, 0.5)',
    containerClass: 'bg-[rgba(4,164,196,0.05)] border-cyan-200/50',
    iconClass: 'text-[#04A4C4]',
    titleKey: 'edit.kpis.totalOvertimeHours.title',
    descKey: 'edit.kpis.totalOvertimeHours.desc',
    statsTitleKey: 'edit.kpis.totalOvertimeHours.title',
  },
  {
    slug: 'overtime_employees',
    category: 'attendance',
    permission: 'attendance:read',
    icon: Users,
    iconColor: '#2A48E0',
    bgColor: 'rgba(42, 72, 224, 0.05)',
    borderColor: 'rgba(42, 72, 224, 0.5)',
    containerClass: 'bg-[rgba(42,72,224,0.05)] border-blue-200/50',
    iconClass: 'text-[#2A48E0]',
    titleKey: 'edit.kpis.overtimeEmployees.title',
    descKey: 'edit.kpis.overtimeEmployees.desc',
    statsTitleKey: 'edit.kpis.overtimeEmployees.title',
  },
  {
    slug: 'pending_leave_requests',
    category: 'leave',
    permission: 'leave_requests:read',
    icon: FileClock,
    iconColor: '#8A38F5',
    bgColor: 'rgba(138, 56, 245, 0.05)',
    borderColor: 'rgba(138, 56, 245, 0.5)',
    containerClass: 'bg-[rgba(138,56,245,0.05)] border-purple-200/50',
    iconClass: 'text-[#8A38F5]',
    titleKey: 'edit.kpis.pendingLeaveRequests.title',
    descKey: 'edit.kpis.pendingLeaveRequests.desc',
    statsTitleKey: 'edit.kpis.pendingLeaveRequests.title',
  },
  {
    slug: 'approved_leave_requests',
    category: 'leave',
    permission: 'leave_requests:read',
    icon: CircleCheck,
    iconColor: '#22C55E',
    bgColor: 'rgba(34, 197, 94, 0.05)',
    borderColor: 'rgba(34, 197, 94, 0.5)',
    containerClass: 'bg-[rgba(34,197,94,0.05)] border-green-200/50',
    iconClass: 'text-[#22C55E]',
    titleKey: 'edit.kpis.approvedLeaveRequests.title',
    descKey: 'edit.kpis.approvedLeaveRequests.desc',
    statsTitleKey: 'edit.kpis.approvedLeaveRequests.title',
  },
  {
    slug: 'rejected_leave_requests',
    category: 'leave',
    permission: 'leave_requests:read',
    icon: FileText,
    iconColor: '#EF4444',
    bgColor: 'rgba(239, 68, 68, 0.05)',
    borderColor: 'rgba(239, 68, 68, 0.5)',
    containerClass: 'bg-[rgba(239,68,68,0.05)] border-red-200/50',
    iconClass: 'text-[#EF4444]',
    titleKey: 'edit.kpis.rejectedLeaveRequests.title',
    descKey: 'edit.kpis.rejectedLeaveRequests.desc',
    statsTitleKey: 'edit.kpis.rejectedLeaveRequests.title',
  },
  {
    slug: 'total_leave_requests',
    category: 'leave',
    permission: 'leave_requests:read',
    icon: Scale,
    iconColor: '#6366F1',
    bgColor: 'rgba(99, 102, 241, 0.05)',
    borderColor: 'rgba(99, 102, 241, 0.5)',
    containerClass: 'bg-[rgba(99,102,241,0.05)] border-indigo-200/50',
    iconClass: 'text-[#6366F1]',
    titleKey: 'edit.kpis.totalLeaveRequests.title',
    descKey: 'edit.kpis.totalLeaveRequests.desc',
    statsTitleKey: 'edit.kpis.totalLeaveRequests.title',
  },
  {
    slug: 'leave_days_remaining',
    category: 'leave',
    permission: 'leave_balances:read',
    icon: CalendarDays,
    iconColor: '#04A4C4',
    bgColor: 'rgba(4, 164, 196, 0.05)',
    borderColor: 'rgba(4, 164, 196, 0.5)',
    containerClass: 'bg-[rgba(4,164,196,0.05)] border-cyan-200/50',
    iconClass: 'text-[#04A4C4]',
    titleKey: 'edit.kpis.leaveDaysRemaining.title',
    descKey: 'edit.kpis.leaveDaysRemaining.desc',
    statsTitleKey: 'edit.kpis.leaveDaysRemaining.title',
  },
  {
    slug: 'active_leave_policies',
    category: 'leave',
    permission: 'leave_policies:read',
    icon: FileStack,
    iconColor: '#8A38F5',
    bgColor: 'rgba(138, 56, 245, 0.05)',
    borderColor: 'rgba(138, 56, 245, 0.5)',
    containerClass: 'bg-[rgba(138,56,245,0.05)] border-purple-200/50',
    iconClass: 'text-[#8A38F5]',
    titleKey: 'edit.kpis.activeLeavePolicies.title',
    descKey: 'edit.kpis.activeLeavePolicies.desc',
    statsTitleKey: 'edit.kpis.activeLeavePolicies.title',
  },
  {
    slug: 'upcoming_payroll',
    category: 'payroll',
    permission: 'payroll_runs:read',
    icon: CalendarDays,
    iconColor: '#04A4C4',
    bgColor: 'rgba(4, 164, 196, 0.05)',
    borderColor: 'rgba(4, 164, 196, 0.5)',
    containerClass: 'bg-[rgba(4,164,196,0.05)] border-cyan-200/50',
    iconClass: 'text-[#04A4C4]',
    titleKey: 'edit.kpis.upcomingPayroll.title',
    descKey: 'edit.kpis.upcomingPayroll.desc',
    statsTitleKey: 'stats.upcomingPayroll',
  },
  {
    slug: 'draft_payroll_runs',
    category: 'payroll',
    permission: 'payroll_runs:read',
    icon: FileText,
    iconColor: '#6366F1',
    bgColor: 'rgba(99, 102, 241, 0.05)',
    borderColor: 'rgba(99, 102, 241, 0.5)',
    containerClass: 'bg-[rgba(99,102,241,0.05)] border-indigo-200/50',
    iconClass: 'text-[#6366F1]',
    titleKey: 'edit.kpis.draftPayrollRuns.title',
    descKey: 'edit.kpis.draftPayrollRuns.desc',
    statsTitleKey: 'edit.kpis.draftPayrollRuns.title',
  },
  {
    slug: 'pending_payroll_runs',
    category: 'payroll',
    permission: 'payroll_runs:read',
    icon: Clock,
    iconColor: '#F59E0B',
    bgColor: 'rgba(245, 158, 11, 0.05)',
    borderColor: 'rgba(245, 158, 11, 0.5)',
    containerClass: 'bg-[rgba(245,158,11,0.05)] border-amber-200/50',
    iconClass: 'text-[#F59E0B]',
    titleKey: 'edit.kpis.pendingPayrollRuns.title',
    descKey: 'edit.kpis.pendingPayrollRuns.desc',
    statsTitleKey: 'edit.kpis.pendingPayrollRuns.title',
  },
  {
    slug: 'paid_payroll_runs',
    category: 'payroll',
    permission: 'payroll_runs:read',
    icon: Banknote,
    iconColor: '#22C55E',
    bgColor: 'rgba(34, 197, 94, 0.05)',
    borderColor: 'rgba(34, 197, 94, 0.5)',
    containerClass: 'bg-[rgba(34,197,94,0.05)] border-green-200/50',
    iconClass: 'text-[#22C55E]',
    titleKey: 'edit.kpis.paidPayrollRuns.title',
    descKey: 'edit.kpis.paidPayrollRuns.desc',
    statsTitleKey: 'edit.kpis.paidPayrollRuns.title',
  },
  {
    slug: 'total_payslips',
    category: 'payroll',
    permission: 'payslips:read',
    icon: FileStack,
    iconColor: '#2A48E0',
    bgColor: 'rgba(42, 72, 224, 0.05)',
    borderColor: 'rgba(42, 72, 224, 0.5)',
    containerClass: 'bg-[rgba(42,72,224,0.05)] border-blue-200/50',
    iconClass: 'text-[#2A48E0]',
    titleKey: 'edit.kpis.totalPayslips.title',
    descKey: 'edit.kpis.totalPayslips.desc',
    statsTitleKey: 'edit.kpis.totalPayslips.title',
  },
  {
    slug: 'compliance_percentage',
    category: 'compliance',
    permission: 'compliance:read',
    icon: Percent,
    iconColor: '#22C55E',
    bgColor: 'rgba(34, 197, 94, 0.05)',
    borderColor: 'rgba(34, 197, 94, 0.5)',
    containerClass: 'bg-[rgba(34,197,94,0.05)] border-green-200/50',
    iconClass: 'text-[#22C55E]',
    trend: 'up',
    titleKey: 'edit.kpis.compliancePercentage.title',
    descKey: 'edit.kpis.compliancePercentage.desc',
    statsTitleKey: 'edit.kpis.compliancePercentage.title',
  },
  {
    slug: 'fully_compliant_employees',
    category: 'compliance',
    permission: 'compliance:read',
    icon: ShieldCheck,
    iconColor: '#22C55E',
    bgColor: 'rgba(34, 197, 94, 0.05)',
    borderColor: 'rgba(34, 197, 94, 0.5)',
    containerClass: 'bg-[rgba(34,197,94,0.05)] border-green-200/50',
    iconClass: 'text-[#22C55E]',
    titleKey: 'edit.kpis.fullyCompliantEmployees.title',
    descKey: 'edit.kpis.fullyCompliantEmployees.desc',
    statsTitleKey: 'edit.kpis.fullyCompliantEmployees.title',
  },
  {
    slug: 'non_compliant_employees',
    category: 'compliance',
    permission: 'compliance:read',
    icon: ShieldAlert,
    iconColor: '#EF4444',
    bgColor: 'rgba(239, 68, 68, 0.05)',
    borderColor: 'rgba(239, 68, 68, 0.5)',
    containerClass: 'bg-[rgba(239,68,68,0.05)] border-red-200/50',
    iconClass: 'text-[#EF4444]',
    trend: 'down',
    titleKey: 'edit.kpis.nonCompliantEmployees.title',
    descKey: 'edit.kpis.nonCompliantEmployees.desc',
    statsTitleKey: 'edit.kpis.nonCompliantEmployees.title',
  },
  {
    slug: 'expiring_documents',
    category: 'compliance',
    permission: 'compliance:read',
    icon: FileWarning,
    iconColor: '#F59E0B',
    bgColor: 'rgba(245, 158, 11, 0.05)',
    borderColor: 'rgba(245, 158, 11, 0.5)',
    containerClass: 'bg-[rgba(245,158,11,0.05)] border-amber-200/50',
    iconClass: 'text-[#F59E0B]',
    titleKey: 'edit.kpis.expiringDocuments.title',
    descKey: 'edit.kpis.expiringDocuments.desc',
    statsTitleKey: 'edit.kpis.expiringDocuments.title',
  },
];

export const ADMIN_KPI_CATALOG_BY_SLUG = Object.fromEntries(
  ADMIN_KPI_CATALOG.map((entry) => [entry.slug, entry]),
) as Record<AdminKpiSlug, AdminKpiCatalogEntry>;
